import numpy as np
from scipy.spatial import ConvexHull
from scipy import optimize

# TODO:  no. of contacts shld be configurable

class WrenchCheck:
    def __init__(self, pos1, pos2, R1, R2, ncf1, ncf2, tan1_y, tan1_z, tan2_y, tan2_z, mu1, mu2):
        '''
        Contact forces (ncf, tan) should result in zero wrench on object 
        (i.e. null space of grasp map)

        Currently assumes 2 contacts in 3D: 1, 2
        -----------------------------------
        :param np.array(3, 1) pos_b: position of contacts in object body frame 
        :param np.array(3, 3) R_bc: contact frame (x: normal, y: tangential, z: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param float ncf: normal contact force magnitude
        :param float tan: tangential contact force magnitude and direction (+ve along dir defined by R_bc)
        :param float mu: tangential friction coefficient
        '''
        self.pos1 = pos1
        self.pos2 = pos2
        self.R1 = R1
        self.R2 = R2
        self.ncf1 = ncf1
        self.ncf2 = ncf2
        self.tan1_y = tan1_y
        self.tan1_z = tan1_z
        self.tan2_y = tan2_y
        self.tan2_z - tan2_z
        self.mu1 = mu1
        self.mu2 = mu2

    def single_wrench_cone(self, gamma, pos_bc, R_bc, ncf, mu):
        '''
        Calculate wrench vertices (Mx, My, Mz, fx, fy, fz) bounding contact wrench cone 
        Wrench cone is then the convex hull of calculated wrench vertices
        -> in body frame 
        -> for a single contact in 3D
        -> assume coulomb friction (which assumes isotropic)

        (Convex hull is smallest convex set that contains all points in the set)
        ---------
        :param np.array(3, 1) pos_b: position of contact in body frame 
        :param np.array(3, 3) R_bc: contact frame (x: normal, y: tangential, z: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param float ncf: normal contact force magnitude
        :param float mu: tangential friction coefficient (mu_y = mu_z since assume isotropic friction)

        :return np.array(5,): wrench vertices in body frame [Mx, My, Mz, fx, fy, fz] bounding contact wrench cone 
        '''
        # 3D friction cone vertices in contact frame
        # Use square pyramidal cone to underestimate actual friction cone 
        ncf = ncf*gamma[0]
        f0_c = np.array([[0], [0], [0]])
        f1_c = np.array([[ncf], [0], [-mu*ncf]])
        f2_c = np.array([[ncf], [-mu*ncf], [0]])
        f3_c = np.array([[ncf], [mu*ncf], [0]])
        f4_c = np.array([[ncf], [0], [mu*ncf]])

        # 3D friction cone vertices in body frame
        f0_b = R_bc @ f0_c
        f1_b = R_bc @ f1_c
        f2_b = R_bc @ f2_c
        f3_b = R_bc @ f3_c
        f4_b = R_bc @ f4_c

        # Torque generated by each contact friction cone vertex, in body frame 
        t0_b = np.cross(pos_bc, f0_b, axisa=0, axisb=0)[0]
        t1_b = np.cross(pos_bc, f1_b, axisa=0, axisb=0)[0]
        t2_b = np.cross(pos_bc, f2_b, axisa=0, axisb=0)[0]
        t3_b = np.cross(pos_bc, f3_b, axisa=0, axisb=0)[0]
        t4_b = np.cross(pos_bc, f4_b, axisa=0, axisb=0)[0]

        # Wrench cone vertices [Mx, My, Mz, fx, fy, fz] in body frame 
        F0_b = np.append(t0_b, f0_b)
        F1_b = np.append(t1_b, f1_b)
        F2_b = np.append(t2_b, f2_b)
        F3_b = np.append(t3_b, f3_b)
        F4_b = np.append(t4_b, f4_b)

        return np.array([F0_b, F1_b, F2_b, F3_b, F4_b])
    
    def in_total_wrench_space(self, wrench, verts1, verts2):
        '''
        Determines whether candidate wrench is in total wrench space generated by contacts 1 & 2
        Total wrench space is minkowski sum (sumset of 2 subsets in Euclidean space) of wrench cones 1 & 2, bounded by vertices 1 & 2

        (Minkowski sum is the sumset of 2 subsets A & B in Euclidean space, i.e. A + B = {a + b, where a in A & b in B})
        (Minkowski sum of 2 convex polygons is equal to the convex hull of Minkowski sum of set of vertices of each polygon)
        --------------
        :param np.array(6, 1) wrench: candidate wrench in body frame
        :param np.array(5, 6) verts1, verts2: array of vertices [Mx, My, Mz, fx, fy, fz] bounding each contact wrench cone           

        :return np.array(no. of constraint eqns,) lhs: right hand side value of wrench space constraint equations
                ^ does not return bool! to be consistent with constraint building for optimizer
        '''
        vert_sums = []

        for vert1 in verts1:
            for vert2 in verts2:
                vert_sums.append(vert1+vert2)
        vert_sums = np.array(vert_sums)
        hull = ConvexHull(vert_sums)

        lhs = []
        for equation in hull.equations:
            # shows coefficient order: https://stackoverflow.com/questions/42248202/find-the-projection-of-a-point-on-the-convex-hull-with-scipy
            val = (equation[:-1] @ wrench + equation[-1])
            lhs.append(val[0])

        # lhs <= 0
        # http://www.qhull.org/html/index.htm#description
        return lhs

    def wrench_feasibility(self, gamma, wrench):
        '''
        Determines feasibility of wrench on object based on 2 null space contacts in 3-D
        -----------
        :param float gamma: where f_contact = f_manipulation + gamma * f_internal
        :param np.array(3, 1) wrench

        :return np.array(no. of constraint eqns,) lhs: right hand side value of wrench space constraint equations, given gamma  
        '''
        verts1 = self.single_wrench_cone(gamma, self.pos1, self.R1, self.ncf1, self.mu1)
        verts2 = self.single_wrench_cone(gamma, self.pos2, self.R2, self.ncf2, self.mu2)

        # Tangential component of gamma * f_interval in contact frame 
        # Gamma[0] to access float from optimizer 
        tan1_c = np.array([[0], [gamma[0] * self.tan1_y], [gamma[0] * self.tan1_z]])
        tan2_c = np.array([[0], [gamma[0] * self.tan2_y], [gamma[0] * self.tan2_z]])

        # Tangential component of gamma * f_interval in body frame 
        tan1_b = self.R1 @ tan1_c
        tan2_b = self.R2 @ tan2_c

        # Torque generated by gamma * f_interval in body frame
        T1_b = np.cross(self.pos1, tan1_b, axisa=0, axisb=0)[0]
        T2_b = np.cross(self.pos2, tan2_b, axisa=0, axisb=0)[0]  

        # Normal contact forces need to support f_manipulation and tangential component of internal forces 
        # Thus to check wrench feasibility of wrench =
        # wrench + wrench due to tangential component of (gamma * f_interval)
        wrench = wrench + np.append(T1_b + T2_b, tan1_b + tan2_b)

        return self.in_total_wrench_space(wrench, verts1, verts2)
    
def min_gamma_for_accel(max_norm_accelx, max_norm_accely, max_norm_accelz, 
                        max_norm_Tx, max_norm_Ty, max_norm_Tz, 
                        pos1, pos2, 
                        R1, R2, 
                        ncf1, ncf2, 
                        tan1_y, tan1_z, tan2_y, tan2_z, 
                        mu1, mu2):
    '''
    Finds minimum gamma (where f_contact = f_manipulation + gamma * f_internal)
    required to ensure no-slip grasp given desired max accelerations and torques in each object body axis
    -----------------------------------------------------------------------------------
    :param float max_norm_accelx, max_norm_accely, max_norm_accelz: maximum magnitude of acceleration along each of x, y, z axis in object body frame
    :param float max_norm_Tx, max_norm_Ty, max_norm_Tz: maximum magnitude of torque about each of x, y, z axis in object body frame
    :param np.array(3, 1) pos_b: position of contacts in body frame 
    :param np.array(3, 3) R_bc: contact frame (x: normal, y: tangential) in terms of body frame 
                                (rotates contact frame to body frame)
    :param float ncf: zero wrench normal contact force magnitude
    :param float tan: zero wrench tangential contact force magnitude and direction (+ve along dir defined by R_bc)
    :param float mu: tangential friction coefficient

    :return float min_gamma: where minimum normal contact force = normal component of (min_gamma * f_internal)
    '''
    wrench_checker = WrenchCheck(pos1, pos2, R1, R2, ncf1, ncf2, tan1_y, tan1_z, tan2_y, tan2_z, mu1, mu2)
    
    constraints = []
    for ax in [-max_norm_accelx, max_norm_accelx]:
        for ay in [-max_norm_accely, max_norm_accely]:
            for az in [-max_norm_accelz, max_norm_accelz]:
                for tx in [-max_norm_Tx, max_norm_Tx]:
                    for ty in [-max_norm_Ty, max_norm_Ty]:
                        for tz in [-max_norm_Tz, max_norm_Tz]:
                            possible_wrench = np.array([[ax], [ay], [az], [tx], [ty], [tz]])
                            
                            # f(gamma) <= 0 
                            # https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.NonlinearConstraint.html#scipy.optimize.NonlinearConstraint
                            f = lambda gamma: wrench_checker.wrench_feasibility(gamma, possible_wrench)
                            constraint = optimize.NonlinearConstraint(f, lb=-np.inf, ub=0)
                            constraints.append(constraint)

    # objective function (since gamma is positive)
    gamma_squared = lambda gamma: gamma[0]**2

    res = optimize.minimize(gamma_squared, x0=1, method='trust-constr', 
                            constraints=constraints)

    return res.x[0] # min_gamma 

if __name__ ==  "__main__":
    # think about how to extend to multiple contacts
    # write test cases 

    a = np.array([[1], [2], [3]])
    b = np.array([[4], [5], [6]])
    c = np.cross(a, b, axisa=0, axisb=0)[0]
    print(f'c: {c}')
    print(f'append: {np.append(a+a, c)}')
    print(f'row to col: {c.reshape(-1, 1)}')
                 