import numpy as np
from scipy.spatial import ConvexHull
from scipy import optimize

class WrenchCheck:
    def __init__(self, pos1, pos2, R1, R2, ncf1, ncf2, tan1, tan2, mu1, mu2):
        '''
        Contact forces (ncf, tan) should result in zero wrench on object 
        (i.e. null space of grasp map)
        --------------------------------------------------------------------
        :param np.array(2, 1) pos_b: position of contacts in object body frame 
        :param np.array(2, 1) R_bc: contact frame (x: normal, y: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param float ncf: normal contact force magnitude
        :param float tan: tangential contact force magnitude and direction (+ve along y-dir defined by R_bc)
        :param float mu: tangential friction coefficient
        '''
        self.pos1 = pos1
        self.pos2 = pos2
        self.R1 = R1
        self.R2 = R2
        self.ncf1 = ncf1
        self.ncf2 = ncf2
        self.tan1 = tan1
        self.tan2 = tan2
        self.mu1 = mu1
        self.mu2 = mu2

    def wrench_feasibility(self, gamma, wrench):
        '''
        Determines feasibility of max wrench on object based on 2 null space contacts in 2-D
        -----------
        :param float gamma: constant that multiplies f_interval 
        :param np.array(3, 1) wrench: = possible max wrench + tangential (in contact frame) component of gamma * f_internal

        :return np.array(12,) rhs: right hand side value of wrench space constraint equations, given gamma  
        '''
        verts1 = self.single_wrench_cone(gamma, self.pos1, self.R1, self.ncf1, self.mu1)
        verts2 = self.single_wrench_cone(gamma, self.pos2, self.R2, self.ncf2, self.mu2)

        # Tangential component of gamma * f_interval in contact frame 
        tan1_c = np.array([[0], [gamma[0] * self.tan1]])
        tan2_c = np.array([[0], [gamma[0] * self.tan2]])

        # Tangential component of gamma * f_interval in body frame 
        tan1_b = self.R1 @ tan1_c
        tan2_b = self.R2 @ tan2_c

        wrench = wrench + np.array([[0], 
                                    [tan1_b[0][0] + tan2_b[0][0]], 
                                    [tan1_b[1][0] + tan2_b[1][0]]])

        return self.in_total_wrench_space(wrench, verts1, verts2)

    def in_total_wrench_space(self, wrench, verts1, verts2):
        '''
        Determines whether candidate wrench is in total wrench space generated by contacts 1 & 2
        Total wrench space is minkowski sum of wrench cones 1 & 2, bounded by vertices 1 & 2
        --------------
        :param np.array(3, 1) wrench: candidate wrench in body frame
        :param np.array(3, 1) verts1, verts2: array of vertices (Mx, fx, fy) bounding each contact wrench cone           

        :return np.array(12,) rhs: right hand side value of wrench space constraint equations
                ^ does not return bool! to be consistent with constraint building for optimizer
        '''
        vert_sums = []

        for vert1 in verts1:
            for vert2 in verts2:
                vert_sums.append(np.reshape(vert1+vert2, (3,)))
        vert_sums = np.array(vert_sums)
        hull = ConvexHull(vert_sums)

        rhs = []
        for equation in hull.equations:
            val = (equation[0]*wrench[0] + equation[1]*wrench[1] + equation[2]*wrench[2]
                    + equation[3])
            rhs.append(val[0])
        return rhs

    def single_wrench_cone(self, gamma, pos_bc, R_bc, ncf, mu):
        '''
        Calculate wrench vertices (Mx, fx, fy) bounding contact wrench cone
        Wrench cone is convex hull of calculated wrench vertices
        ---------
        :param np.array(2, 1) pos_b: in body frame 
        :param np.array(2, 1) R_bc: contact frame (x: normal, y: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param float ncf: normal contact force magnitude
        :param float mu: tangential friction coefficient

        :return np.array(3, 1): wrench vertices (Mx, fx, fy) bounding contact wrench cone 
        '''
        # 2D friction cone vertices in contact frame
        ncf = ncf*gamma[0]
        f0_c = np.array([[0], [0]])
        f1_c = np.array([[ncf], [-mu*ncf]])
        f2_c = np.array([[ncf], [mu*ncf]])

        # 2D friction cone vertices in body frame
        f0_b = R_bc @ f0_c
        f1_b = R_bc @ f1_c
        f2_b = R_bc @ f2_c

        # Wrench cone vertices (Mx, fx, fy) in body frame 
        F0_b = np.array([pos_bc[0]*f0_b[1] - pos_bc[1]*f0_b[0], f0_b[0], f0_b[1]])
        F1_b = np.array([pos_bc[0]*f1_b[1] - pos_bc[1]*f1_b[0], f1_b[0], f1_b[1]])
        F2_b = np.array([pos_bc[0]*f2_b[1] - pos_bc[1]*f2_b[0], f2_b[0], f2_b[1]])

        return np.array([F0_b, F1_b, F2_b])
    
def min_gamma_for_accel(max_norm_accelx, max_norm_accely, max_norm_torque, pos1, pos2, R1, R2, ncf1, ncf2, tan1, tan2, mu1, mu2):
    '''
    Finds minimum gamma (where f_contact = f_manipulation + gamma * f_internal)
    required to ensure no-slip grasp given desired max accelerations and torques in each object body axis
    -----------------------------------------------------------------------------------
    :param float max_norm_accelx, max_norm_accely: maximum magnitude of acceleration along each of x, y axis in object frame
    :param float max_norm_torque: maximum magnitude of torque about z axis in object frame
    :param np.array(2, 1) pos_b: position of contacts in body frame 
    :param np.array(2, 1) R_bc: contact frame (x: normal, y: tangential) in terms of body frame 
                                (rotates contact frame to body frame)
    :param float ncf: normal contact force magnitude
    :param float tan: tangential contact force magnitude and direction (+ve along y-dir defined by R_bc)
    :param float mu: tangential friction coefficient

    :return float min_gamma: where minimum normal contact force = normal component of min_gamma * f_internal
    '''
    wrench_checker = WrenchCheck(pos1, pos2, R1, R2, ncf1, ncf2, tan1, tan2, mu1, mu2)
    
    constraints = []
    for ax in [-max_norm_accelx, max_norm_accelx]:
        for ay in [-max_norm_accely, max_norm_accely]:
            for tz in [-max_norm_torque, max_norm_torque]:
                possible_wrench = np.array([[ax], [ay], [tz]])
                f = lambda gamma: wrench_checker.wrench_feasibility(gamma, possible_wrench)
                constraint = optimize.NonlinearConstraint(f, lb=np.zeros(12), ub=np.inf)
                constraints.append(constraint)

    # objective function (since gamma is positive)
    gamma_squared = lambda gamma: gamma[0]**2

    res = optimize.minimize(gamma_squared, x0=1, method='trust-constr', 
                            constraints=constraints)

    return res.x[0] # min_gamma 