import numpy as np
from scipy.spatial import ConvexHull
from scipy import optimize
from scipy.optimize import linprog
from scipy.optimize import Bounds
from itertools import product as iterproduct

# TODO: write methods section overleaf
# -> equations and explanation of this script 
# -> follow convention for variable names, update variable name section as needed
# TODO: change brute force convex hull method to LP and make sure it still works
# TODO: add soft contact model as an option 
# -> implement soft contact model, similar to how implemented coulomb friction model
# -> make sure it werk

class WrenchCheck:
    def __init__(self, n, pos, R, ncf, tan_y, tan_z, mu):
        '''
        Contact forces (ncf, tan) should result in zero wrench on object 
        (i.e. null space of grasp map)

        Currently assumes n contacts in 3D
        -----------------------------------
        :param float n: no. of contacts
        :param list of np.array(3, 1) pos_b: position of contacts in object body frame 
        :param list of np.array(3, 3) R_bc: contact frame (x: normal, y: tangential, z: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param list of float ncf: normal contact force magnitude
        :param list of float tan_y: tangential contact force magnitude and direction (+ve along y-dir defined by R_bc)
        :param list of float tan_z: tangential contact force magnitude and direction (+ve along z-dir defined by R_bc)
        :param list of float mu: tangential friction coefficient
        '''
        
        # check that all inputs are list of length n (internal size errors not checked) 
        if len(pos) != n:
            raise ValueError('No. of contact positions (pos) given not equal to n')
        elif len(R) != n:
            raise ValueError('No. of contact frames (R) given not equal to n')
        elif len(ncf) != n:
            raise ValueError('No. of normal contact force magnitudes (ncf) given not equal to n')
        elif len(tan_y) != n:
            raise ValueError('No. of tangential contact force magnitude & direction in y-dir (tan_y) given not equal to n')
        elif len(tan_z) != n:
            raise ValueError('No. of tangential contact force magnitude & direction in z-dir (tan_z) given not equal to n')  
        elif len(mu) != n:
            raise ValueError('No. of tangential friction coefficients (mu) given not equal to n')  

        self.n = n # no. of contacts
        self.pos = pos
        self.R = R
        self.ncf = ncf
        self.tan_y = tan_y
        self.tan_z = tan_z
        self.mu = mu

        self.num_tol = 1e-10
        self.dim_dict = {0: 'Tx',
                         1: 'Ty',
                         2: 'Tz',
                         3: 'Fx',
                         4: 'Fy',
                         5: 'Fz'}
        
        self.ndims = 6 # 3D, ndims for wrench 
        self.nverts = 5 # no. of vertices per contact

    def single_wrench_cone(self, gamma, pos_bc, R_bc, ncf, mu):
        '''
        Calculate wrench vertices (Tx, Ty, Tz, Fx, Fy, Fz) bounding contact wrench cone 
        Wrench cone is then the convex hull of calculated wrench vertices
        -> in body frame 
        -> for a single contact in 3D
        -> assume coulomb friction (which assumes isotropic)

        (Convex hull is smallest convex set that contains all points in the set)
        (if convex hull has vertices x, y, z, then any vector a*x + b*y + c*z where 
         a, b, c >= 0 and a + b + c <= 1, is in the convex hull)
        ---------
        :param float gamma: where f_contact = f_manipulation + gamma * f_internal
        :param np.array(3, 1) pos_b: position of contact in body frame 
        :param np.array(3, 3) R_bc: contact frame (x: normal, y: tangential, z: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param float ncf: normal contact force magnitude
        :param float mu: tangential friction coefficient (mu_y = mu_z since assume isotropic friction)

        :return np.array(5,): wrench vertices in body frame [Tx, Ty, Tz, Fx, Fy, Fz] bounding contact wrench cone 
        '''
        # 3D friction cone vertices in contact frame
        # Use square pyramidal cone to underestimate actual friction cone 
        ncf = ncf*gamma
        f0_c = np.array([[0], [0], [0]])
        f1_c = np.array([[ncf], [0], [-mu*ncf]])
        f2_c = np.array([[ncf], [-mu*ncf], [0]])
        f3_c = np.array([[ncf], [mu*ncf], [0]])
        f4_c = np.array([[ncf], [0], [mu*ncf]])

        # 3D friction cone vertices in body frame
        f0_b = R_bc @ f0_c
        f1_b = R_bc @ f1_c
        f2_b = R_bc @ f2_c
        f3_b = R_bc @ f3_c
        f4_b = R_bc @ f4_c

        # Torque generated by each contact friction cone vertex, in body frame 
        t0_b = np.cross(pos_bc, f0_b, axisa=0, axisb=0)[0]
        t1_b = np.cross(pos_bc, f1_b, axisa=0, axisb=0)[0]
        t2_b = np.cross(pos_bc, f2_b, axisa=0, axisb=0)[0]
        t3_b = np.cross(pos_bc, f3_b, axisa=0, axisb=0)[0]
        t4_b = np.cross(pos_bc, f4_b, axisa=0, axisb=0)[0]

        # Wrench cone vertices [Tx, Ty, Tz, Fx, Fy, Fz] in body frame 
        F0_b = np.append(t0_b, f0_b)
        F1_b = np.append(t1_b, f1_b)
        F2_b = np.append(t2_b, f2_b)
        F3_b = np.append(t3_b, f3_b)
        F4_b = np.append(t4_b, f4_b)

        return np.array([F0_b, F1_b, F2_b, F3_b, F4_b])
    
    def in_total_wrench_space(self, wrench, verts_list):
        '''
        Determines whether candidate wrench is in total wrench space generated by n contacts 
        Total wrench space is minkowski sum (sumset of n subsets in Euclidean space) of n wrench cones, each bounded by vertices 

        (Minkowski sum of n convex polygons is equal to the convex hull of Minkowski sum (i.e. all possible combinations of sums) of set of vertices of each polygon)
        (e.g. Minkowski sum is the sumset of 3 subsets A & B & C in Euclidean space, i.e. A + B + C = {a + b + c, where a in A & b in B & c in C})
        --------------
        :param np.array(6, 1) wrench: candidate wrench in body frame
        :param np.array(no. of contacts * no. of wrench vertices per contact, 6) verts_list: array of vertices [Tx, Ty, Tz, Fx, Fy, Fz] bounding each contact wrench cone           

        :return np.array(no. of constraint eqns,) lhs: right hand side value of wrench space constraint equations
                ^ does not return bool! to be consistent with constraint building for optimizer
        '''

        # Check if wrench is linear combination of wrench cones of each contact, 
        # where sum of coefficients of vertices from each contact < 1
        ntotal_verts = self.n * self.nverts

        # wrench = verts_list.T @ coeffs
        # A_eq @ x == b_eq
        A_eq = verts_list.T
        b_eq = wrench.flatten()

        # sum of coefficients of vertices for each contact <= 1
        # A_ub @ x <= b_ub
        A_ub = np.zeros((self.n, ntotal_verts)) 
        for i in range(self.n):
            A_ub[i, i*self.nverts:(i+1)*self.nverts] = 1 # select coefficients from same contact
        b_ub = np.ones(self.n) # enforces that coefficients from same contact sum to 1

        # each coefficient should be between 0 and 1 
        bounds = [(0, 1)] * ntotal_verts

        res = linprog(c=np.zeros(ntotal_verts), 
                      A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub, bounds=bounds)
        
        # (0: wrench IS IN total wrench space)
        # (1: wrench is NOT in total wrench space) 
        return 0.0 if res.success else 1.0

    def wrench_feasibility(self, gamma, wrench):
        '''
        Determines feasibility of wrench on object based on n null space contacts in 3-D
        -----------
        :param float gamma: where f_contact = f_manipulation + gamma * f_internal
        :param np.array(6, 1) wrench

        :return np.array(no. of constraint eqns,) lhs: left hand side value of wrench space constraint equations (lhs <= 0), given gamma  
        '''
        verts_list = np.array([np.zeros(self.ndims)]) # will result in first element of verts_list being irrelevant
        torques_list = []
        tans_list = []

        for i in range(self.n):
            vert = self.single_wrench_cone(gamma, self.pos[i], self.R[i], self.ncf[i], self.mu[i])
            verts_list = np.concatenate([verts_list, vert], axis=0)

            # Tangential component of gamma * f_interval in contact frame 
            tan_c = np.array([[0], [gamma * self.tan_y[i]], [gamma * self.tan_z[i]]])

            # Tangential component of gamma * f_interval in body frame 
            tan_b = self.R[i] @ tan_c # (3,1)
            tans_list.append(tan_b)

            # Torque generated by gamma * f_interval in body frame
            torque_b = np.cross(self.pos[i], tan_b, axisa=0, axisb=0)[0] # (3,)
            torques_list.append(torque_b)

        verts_list = verts_list[1:] # first element is irrelevant 
        # verts_list: np.array(no. of contacts * no. of wrench vertices per contact,)
        tans_arr = np.array(tans_list)
        torques_arr = np.array(torques_list)

        # Normal contact forces need to support f_manipulation and tangential component of internal forces 
        # Thus to check wrench feasibility of wrench =
        # wrench + wrench due to tangential component of (gamma * f_interval)
        tan_wrench = np.append(torques_arr.sum(axis=0), tans_arr.sum(axis=0)) # (6,)
        tan_wrench = tan_wrench.reshape(6, 1)
        wrench = wrench + tan_wrench

        return self.in_total_wrench_space(wrench, verts_list)
    
def min_gamma_for_accel(max_norm_accelx, max_norm_accely, max_norm_accelz, 
                        max_norm_Tx, max_norm_Ty, max_norm_Tz, 
                        n, pos, R, ncf, tan_y, tan_z, mu):
    '''
    Finds minimum gamma (where f_contact = f_manipulation + gamma * f_internal)
    required to ensure no-slip grasp given desired max accelerations and torques in each object body axis

    Assuming m = 1 for now (so accel == force)
    -----------------------------------------------------------------------------------
    :param float max_norm_accelx, max_norm_accely, max_norm_accelz: maximum magnitude of acceleration along each of x, y, z axis in object body frame
    :param float max_norm_Tx, max_norm_Ty, max_norm_Tz: maximum magnitude of torque about each of x, y, z axis in object body frame
    :param float n: no. of contacts
    :param list of np.array(3, 1) pos_b: position of contacts in body frame 
    :param list of np.array(3, 3) R_bc: contact frame (x: normal, y: tangential) in terms of body frame 
                                (rotates contact frame to body frame)
    :param list of float ncf: zero wrench normal contact force magnitude
    :param list of float tan: zero wrench tangential contact force magnitude and direction (+ve along dir defined by R_bc)
    :param list of float mu: tangential friction coefficient

    :return float min_gamma: where minimum normal contact force = normal component of (min_gamma * f_internal)
    '''

    wrench_checker = WrenchCheck(n, pos, R, ncf, tan_y, tan_z, mu)

    # collect unique nonzero wrenches
    possible_wrenches = []
    seen = set()
    for tx in [-max_norm_Tx, max_norm_Tx]:
        for ty in [-max_norm_Ty, max_norm_Ty]:
            for tz in [-max_norm_Tz, max_norm_Tz]:
                for ax in [-max_norm_accelx, max_norm_accelx]:
                    for ay in [-max_norm_accely, max_norm_accely]:
                        for az in [-max_norm_accelz, max_norm_accelz]:
                            possible_wrench = np.array([[tx],[ty],[tz],[ax],[ay],[az]])

                            # skip if zero wrench (trivially feasible)
                            # (makes binary search way quicker)
                            if np.allclose(possible_wrench, 0):
                                continue

                            # skip if duplicate possible wrench
                            # (makes binary search way quicker)
                            possible_duplicate = tuple(possible_wrench.flatten())
                            if possible_duplicate in seen:
                                continue
                            seen.add(possible_duplicate)

                            possible_wrenches.append(possible_wrench)

    def all_feasible(gamma):
        return all(wrench_checker.wrench_feasibility(gamma, possible_wrench) < wrench_checker.num_tol
                   for possible_wrench in possible_wrenches)

    # check geometric feasibility at high gamma
    if not all_feasible(1000):
        return None

    # binary search for minimum gamma
    lo, hi = 0.0, 1000.0
    for _ in range(60):  # 60 iterations → precision ~1e-15
        mid = (lo + hi) / 2
        if all_feasible(mid):
            hi = mid
        else:
            lo = mid

    return hi

def min_gamma_for_accel_lp(max_norm_accelx, max_norm_accely, max_norm_accelz,
                           max_norm_Tx, max_norm_Ty, max_norm_Tz,
                           n, pos, R, ncf, tan_y, tan_z, mu,
                           moment_ref=None, grav_force=None,
                           project_grasp_axis_moment=False):
    '''
    Alternative to min_gamma_for_accel: solves minimum gamma directly with one LP per corner wrench
    instead of binary search over feasibility LPs (exact answer, ~60x fewer LP solves)

    Wrench cone vertices scale linearly with gamma (V(gamma) = gamma * V(1)), so substituting
    y = gamma * x (valid since gamma >= 0) makes the problem linear in (y, gamma):
        min  gamma
        s.t. V(1).T @ y - gamma * w_tan = wrench       (w_tan: wrench due to tangential component of f_internal at gamma = 1)
             sum of y coefficients within each contact - gamma <= 0
             y >= 0, gamma >= 0
    Infeasible LP <=> grasp geometrically cannot resist wrench (no gamma cap needed)
    -----------------------------------------------------------------------------------
    :params: same as min_gamma_for_accel

    MOMENT REFERENCE (moment_ref):
      By default all moments (contact p x f AND the corner wrenches) are taken about the
      object CoM (pos is contact-minus-center). For a RAISED antipodal grasp this is the
      wrong datum: a pure lateral force about the CoM implies a spurious moment dz*F that
      the two-point geometry cannot supply, so raising the contacts off the CoM plane
      makes the grasp report INFEASIBLE even though it can physically hold the object.

      Passing moment_ref = (3,) point (SAME frame/origin as `pos`, i.e. relative to the
      object center) re-datums the moment balance to that point — set it to the grasp
      midpoint 0.5*(p1+p2) so a pure lateral disturbance induces NO moment (the contacts
      sit at zero height relative to their own connecting line). This is a pure change of
      reference point (statically equivalent), NOT a relaxation.

      Because the accel-disturbance corner wrenches are FORCES (they translate freely to
      any reference), they are unchanged by the shift. GRAVITY, however, acts at the CoM:
      about a shifted reference it contributes a real moment r x (m g), r = (CoM - ref) =
      -moment_ref (pos is CoM-relative). Pass grav_force = (3,) the gravity force vector
      m*g in the SAME frame as pos/R; its re-datum moment (-moment_ref) x grav_force is
      ADDED to every corner. (For a grasp midpoint directly above the CoM, moment_ref is
      purely vertical and grav_force purely vertical, so the cross product is zero and
      gravity is unaffected — but the term is computed honestly for the general case.)
      grav_force defaults to None (no gravity re-datum) which is correct when the corners
      do not fold gravity into them.

    project_grasp_axis_moment (n==2 only): zero the grasp-axis component of the GRAVITY
      moment. A two-point pinch cannot resist torque about the line through its contacts;
      when the grasp midpoint is off-CoM, gravity about the datum induces such a torque
      that would (wrongly) make the grasp report infeasible even though it can carry the
      object. This extends the grasp-axis projection already applied to the accel torque
      budget (see solve_gamma_live) to the gravity moment. Only meaningful with grav_force
      set. Default False.

    :return float min_gamma: where minimum normal contact force = normal component of (min_gamma * f_internal)
                             None if no gamma can resist the requested wrenches
    '''
    # Re-datum contact positions to the moment reference (grasp point) if requested.
    if moment_ref is not None:
        _ref = np.asarray(moment_ref, float).reshape(3)
        pos = [np.asarray(p, float).reshape(3, 1) - _ref.reshape(3, 1) for p in pos]

    wrench_checker = WrenchCheck(n, pos, R, ncf, tan_y, tan_z, mu)
    nverts = wrench_checker.nverts

    # Gravity as an explicit constant wrench added to EVERY corner. Its FORCE is always
    # present (invariant); its MOMENT depends on the reference: about the reference point,
    # gravity acts at the CoM, arm r = (CoM - ref). pos is CoM-relative so with a shifted
    # reference the contact positions were re-datumed above; the CoM sits at (0 - ref) =
    # -moment_ref relative to the reference (or 0 when moment_ref is None -> CoM ref).
    # _grav_wrench = [moment(3), force(3)] in the [Tx,Ty,Tz,Fx,Fy,Fz] convention.
    _grav_wrench = np.zeros(6)
    if grav_force is not None:
        _gf = np.asarray(grav_force, float).reshape(3)
        _r_cg = (-np.asarray(moment_ref, float).reshape(3)
                 if moment_ref is not None else np.zeros(3))       # CoM relative to ref
        _grav_wrench[:3] = np.cross(_r_cg, _gf)                     # gravity moment
        _grav_wrench[3:] = _gf                                      # gravity force (always)

        # Grasp-axis projection of the gravity MOMENT (n==2 only). A two-contact pinch
        # cannot resist torque about the grasp axis (the line through the contacts): the
        # friction-cone forces have no moment arm about it. When the grasp midpoint is
        # off-CoM (e.g. slid along the face), gravity about the datum induces a moment
        # whose grasp-axis component is unresistable and would make the LP report None,
        # even though the grasp can carry the object. Zero that component — the same
        # principle already applied to the accel TORQUE budget by callers (solve_gamma_live
        # / the NLP), extended here to the gravity moment. Only the grasp-axis component is
        # removed; the perpendicular moment (which the grasp CAN resist) is kept honest.
        if project_grasp_axis_moment and n == 2:
            _ga = (np.asarray(pos[1], float).reshape(3)
                   - np.asarray(pos[0], float).reshape(3))
            _gn = np.linalg.norm(_ga)
            if _gn > 1e-9:
                _ga = _ga / _gn
                _m = _grav_wrench[:3]
                _grav_wrench[:3] = _m - np.dot(_m, _ga) * _ga      # kill grasp-axis torque

    # cone vertices and tangential-internal-force wrench at gamma = 1
    V1 = np.vstack([wrench_checker.single_wrench_cone(1.0, pos[i], R[i], ncf[i], mu[i])
                    for i in range(n)]) # (n * nverts, 6)
    w_tan = np.zeros(6)
    for i in range(n):
        tan_b = R[i] @ np.array([[0.0], [tan_y[i]], [tan_z[i]]])
        w_tan[:3] += np.cross(pos[i], tan_b, axisa=0, axisb=0)[0]
        w_tan[3:] += tan_b.flatten()

    # variables: [y (n * nverts), gamma]
    nvar = n * nverts + 1
    c = np.zeros(nvar)
    c[-1] = 1.0 # min gamma
    A_eq = np.hstack([V1.T, -w_tan.reshape(6, 1)]) # (6, nvar)
    A_ub = np.zeros((n, nvar))
    for k in range(n):
        A_ub[k, k*nverts:(k+1)*nverts] = 1 # select coefficients from same contact
        A_ub[k, -1] = -1
    b_ub = np.zeros(n)
    bounds = [(0, None)] * nvar

    # collect unique nonzero corner wrenches
    corners = set()
    for tx in [-max_norm_Tx, max_norm_Tx]:
        for ty in [-max_norm_Ty, max_norm_Ty]:
            for tz in [-max_norm_Tz, max_norm_Tz]:
                for ax in [-max_norm_accelx, max_norm_accelx]:
                    for ay in [-max_norm_accely, max_norm_accely]:
                        for az in [-max_norm_accelz, max_norm_accelz]:
                            corner = (tx, ty, tz, ax, ay, az)
                            if any(corner):
                                corners.add(corner)

    # Gravity (when passed as grav_force) is a CONSTANT wrench [T(3), F(3)] added to every
    # corner before the LP: force always present, moment reference-dependent (see above).
    min_gamma = 0.0
    for corner in corners:
        _b = np.array(corner, float) + _grav_wrench
        res = linprog(c=c, A_eq=A_eq, b_eq=_b, A_ub=A_ub, b_ub=b_ub, bounds=bounds)
        if not res.success:
            return None
        min_gamma = max(min_gamma, res.x[-1])

    return min_gamma

if __name__ ==  "__main__":

    print('sign convention: z↑ x-> y⊗')

    # ->▢ <- from spatial_grasp_map.py
    n_contacts = 2
    pos_list = [np.array([[-0.05], [0], [0]]), np.array([[0.05], [0], [0]])]
    R_list = [np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), np.array([[-1, 0, 0], [0, 1, 0], [0, 0, 1]])]
    ncf_list = [1, 1]
    tany_list = [0, 0]
    tanz_list = [0, 0]
    mu_list = [1, 1]
    
    # Test 1: ->▢ <- with wrench ->
    print('Test 1: ->▢ <- with wrench ->')
    print(f'When fx=1 wrench, gamma = {min_gamma_for_accel(1, 0, 0, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')
    print(f'              (single LP) {min_gamma_for_accel_lp(1, 0, 0, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 2: ->▢ <- with wrench ⊗
    print('Test 2: ->▢ <- with wrench ⊗')
    print(f'When fy=1 wrench, gamma = {min_gamma_for_accel(0, 1, 0, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')
    print(f'              (single LP) {min_gamma_for_accel_lp(0, 1, 0, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 3: ->▢ <- with wrench ↑
    print('Test 3: ->▢ <- with wrench  ↑')
    print(f'When fz=1 wrench, gamma = {min_gamma_for_accel(0, 0, 1, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')
    print(f'              (single LP) {min_gamma_for_accel_lp(0, 0, 1, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 4: ->▢ <- with wrench torque about x-axis
    print('Test 4: ->▢ <- with wrench torque about x-axis')
    print(f'When Tx=1 wrench, gamma = {min_gamma_for_accel(0, 0, 0, 1, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')
    print(f'              (single LP) {min_gamma_for_accel_lp(0, 0, 0, 1, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 5: ->▢ <- with wrench torque about y-axis
    print('Test 5: ->▢ <- with wrench torque about y-axis')
    print(f'When Ty=1 wrench, gamma = {min_gamma_for_accel(0, 0, 0, 0, 1, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')
    print(f'              (single LP) {min_gamma_for_accel_lp(0, 0, 0, 0, 1, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 6: ->▢ <- with wrench torque about z-axis
    print('Test 6: ->▢ <- with wrench torque about z-axis')
    print(f'When Tz=1 wrench, gamma = {min_gamma_for_accel(0, 0, 0, 0, 0, 1, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')
    print(f'              (single LP) {min_gamma_for_accel_lp(0, 0, 0, 0, 0, 1, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    print()


                