import numpy as np
from scipy.spatial import ConvexHull
from scipy import optimize
from scipy.optimize import linprog
from scipy.optimize import Bounds
from itertools import product as iterproduct

# TODO: write methods section overleaf
# -> equations and explanation of this script 
# -> follow convention for variable names, update variable name section as needed
# TODO: change brute force convex hull method to LP and make sure it still works
# TODO: add soft contact model as an option 
# -> implement soft contact model, similar to how implemented coulomb friction model
# -> make sure it werk

class WrenchCheck:
    def __init__(self, n, pos, R, ncf, tan_y, tan_z, mu):
        '''
        Contact forces (ncf, tan) should result in zero wrench on object 
        (i.e. null space of grasp map)

        Currently assumes n contacts in 3D
        -----------------------------------
        :param float n: no. of contacts
        :param list of np.array(3, 1) pos_b: position of contacts in object body frame 
        :param list of np.array(3, 3) R_bc: contact frame (x: normal, y: tangential, z: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param list of float ncf: normal contact force magnitude
        :param list of float tan_y: tangential contact force magnitude and direction (+ve along y-dir defined by R_bc)
        :param list of float tan_z: tangential contact force magnitude and direction (+ve along z-dir defined by R_bc)
        :param list of float mu: tangential friction coefficient
        '''
        
        # check that all inputs are list of length n (internal size errors not checked) 
        if len(pos) != n:
            raise ValueError('No. of contact positions (pos) given not equal to n')
        elif len(R) != n:
            raise ValueError('No. of contact frames (R) given not equal to n')
        elif len(ncf) != n:
            raise ValueError('No. of normal contact force magnitudes (ncf) given not equal to n')
        elif len(tan_y) != n:
            raise ValueError('No. of tangential contact force magnitude & direction in y-dir (tan_y) given not equal to n')
        elif len(tan_z) != n:
            raise ValueError('No. of tangential contact force magnitude & direction in z-dir (tan_z) given not equal to n')  
        elif len(mu) != n:
            raise ValueError('No. of tangential friction coefficients (mu) given not equal to n')  

        self.n = n # no. of contacts
        self.pos = pos
        self.R = R
        self.ncf = ncf
        self.tan_y = tan_y
        self.tan_z = tan_z
        self.mu = mu

        self.num_tol = 1e-10
        self.dim_dict = {0: 'Tx',
                         1: 'Ty',
                         2: 'Tz',
                         3: 'Fx',
                         4: 'Fy',
                         5: 'Fz'}
        
        self.ndims = 6 # 3D, ndims for wrench 
        self.nverts = 5 # no. of vertices per contact

    def single_wrench_cone(self, gamma, pos_bc, R_bc, ncf, mu):
        '''
        Calculate wrench vertices (Tx, Ty, Tz, Fx, Fy, Fz) bounding contact wrench cone 
        Wrench cone is then the convex hull of calculated wrench vertices
        -> in body frame 
        -> for a single contact in 3D
        -> assume coulomb friction (which assumes isotropic)

        (Convex hull is smallest convex set that contains all points in the set)
        (if convex hull has vertices x, y, z, then any vector a*x + b*y + c*z where 
         a, b, c >= 0 and a + b + c <= 1, is in the convex hull)
        ---------
        :param float gamma: where f_contact = f_manipulation + gamma * f_internal
        :param np.array(3, 1) pos_b: position of contact in body frame 
        :param np.array(3, 3) R_bc: contact frame (x: normal, y: tangential, z: tangential) in terms of body frame 
                                    (rotates contact frame to body frame)
        :param float ncf: normal contact force magnitude
        :param float mu: tangential friction coefficient (mu_y = mu_z since assume isotropic friction)

        :return np.array(5,): wrench vertices in body frame [Tx, Ty, Tz, Fx, Fy, Fz] bounding contact wrench cone 
        '''
        # 3D friction cone vertices in contact frame
        # Use square pyramidal cone to underestimate actual friction cone 
        ncf = ncf*gamma
        f0_c = np.array([[0], [0], [0]])
        f1_c = np.array([[ncf], [0], [-mu*ncf]])
        f2_c = np.array([[ncf], [-mu*ncf], [0]])
        f3_c = np.array([[ncf], [mu*ncf], [0]])
        f4_c = np.array([[ncf], [0], [mu*ncf]])

        # 3D friction cone vertices in body frame
        f0_b = R_bc @ f0_c
        f1_b = R_bc @ f1_c
        f2_b = R_bc @ f2_c
        f3_b = R_bc @ f3_c
        f4_b = R_bc @ f4_c

        # Torque generated by each contact friction cone vertex, in body frame 
        t0_b = np.cross(pos_bc, f0_b, axisa=0, axisb=0)[0]
        t1_b = np.cross(pos_bc, f1_b, axisa=0, axisb=0)[0]
        t2_b = np.cross(pos_bc, f2_b, axisa=0, axisb=0)[0]
        t3_b = np.cross(pos_bc, f3_b, axisa=0, axisb=0)[0]
        t4_b = np.cross(pos_bc, f4_b, axisa=0, axisb=0)[0]

        # Wrench cone vertices [Tx, Ty, Tz, Fx, Fy, Fz] in body frame 
        F0_b = np.append(t0_b, f0_b)
        F1_b = np.append(t1_b, f1_b)
        F2_b = np.append(t2_b, f2_b)
        F3_b = np.append(t3_b, f3_b)
        F4_b = np.append(t4_b, f4_b)

        return np.array([F0_b, F1_b, F2_b, F3_b, F4_b])
    
    def in_total_wrench_space(self, wrench, verts_list):
        '''
        Determines whether candidate wrench is in total wrench space generated by n contacts 
        Total wrench space is minkowski sum (sumset of n subsets in Euclidean space) of n wrench cones, each bounded by vertices 

        (Minkowski sum of n convex polygons is equal to the convex hull of Minkowski sum (i.e. all possible combinations of sums) of set of vertices of each polygon)
        (e.g. Minkowski sum is the sumset of 3 subsets A & B & C in Euclidean space, i.e. A + B + C = {a + b + c, where a in A & b in B & c in C})
        --------------
        :param np.array(6, 1) wrench: candidate wrench in body frame
        :param np.array(no. of contacts * no. of wrench vertices per contact, 6) verts_list: array of vertices [Tx, Ty, Tz, Fx, Fy, Fz] bounding each contact wrench cone           

        :return np.array(no. of constraint eqns,) lhs: right hand side value of wrench space constraint equations
                ^ does not return bool! to be consistent with constraint building for optimizer
        '''

        # Check if wrench is linear combination of wrench cones of each contact, 
        # where sum of coefficients of vertices from each contact < 1
        ntotal_verts = self.n * self.nverts

        # wrench = verts_list.T @ coeffs
        # A_eq @ x == b_eq
        A_eq = verts_list.T
        b_eq = wrench.flatten()

        # sum of coefficients of vertices for each contact <= 1
        # A_ub @ x <= b_ub
        A_ub = np.zeros((self.n, ntotal_verts)) 
        for i in range(self.n):
            A_ub[i, i*self.nverts:(i+1)*self.nverts] = 1 # select coefficients from same contact
        b_ub = np.ones(self.n) # enforces that coefficients from same contact sum to 1

        # each coefficient should be between 0 and 1 
        bounds = [(0, 1)] * ntotal_verts

        res = linprog(c=np.zeros(ntotal_verts), 
                      A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub, bounds=bounds)
        
        # (0: wrench IS IN total wrench space)
        # (1: wrench is NOT in total wrench space) 
        return 0.0 if res.success else 1.0

    def wrench_feasibility(self, gamma, wrench):
        '''
        Determines feasibility of wrench on object based on n null space contacts in 3-D
        -----------
        :param float gamma: where f_contact = f_manipulation + gamma * f_internal
        :param np.array(6, 1) wrench

        :return np.array(no. of constraint eqns,) lhs: left hand side value of wrench space constraint equations (lhs <= 0), given gamma  
        '''
        verts_list = np.array([np.zeros(self.ndims)]) # will result in first element of verts_list being irrelevant
        torques_list = []
        tans_list = []

        for i in range(self.n):
            vert = self.single_wrench_cone(gamma, self.pos[i], self.R[i], self.ncf[i], self.mu[i])
            verts_list = np.concatenate([verts_list, vert], axis=0)

            # Tangential component of gamma * f_interval in contact frame 
            tan_c = np.array([[0], [gamma * self.tan_y[i]], [gamma * self.tan_z[i]]])

            # Tangential component of gamma * f_interval in body frame 
            tan_b = self.R[i] @ tan_c # (3,1)
            tans_list.append(tan_b)

            # Torque generated by gamma * f_interval in body frame
            torque_b = np.cross(self.pos[i], tan_b, axisa=0, axisb=0)[0] # (3,)
            torques_list.append(torque_b)

        verts_list = verts_list[1:] # first element is irrelevant 
        # verts_list: np.array(no. of contacts * no. of wrench vertices per contact,)
        tans_arr = np.array(tans_list)
        torques_arr = np.array(torques_list)

        # Normal contact forces need to support f_manipulation and tangential component of internal forces 
        # Thus to check wrench feasibility of wrench =
        # wrench + wrench due to tangential component of (gamma * f_interval)
        tan_wrench = np.append(torques_arr.sum(axis=0), tans_arr.sum(axis=0)) # (6,)
        tan_wrench = tan_wrench.reshape(6, 1)
        wrench = wrench + tan_wrench

        return self.in_total_wrench_space(wrench, verts_list)
    
def min_gamma_for_accel(max_norm_accelx, max_norm_accely, max_norm_accelz, 
                        max_norm_Tx, max_norm_Ty, max_norm_Tz, 
                        n, pos, R, ncf, tan_y, tan_z, mu):
    '''
    Finds minimum gamma (where f_contact = f_manipulation + gamma * f_internal)
    required to ensure no-slip grasp given desired max accelerations and torques in each object body axis

    Assuming m = 1 for now (so accel == force)
    -----------------------------------------------------------------------------------
    :param float max_norm_accelx, max_norm_accely, max_norm_accelz: maximum magnitude of acceleration along each of x, y, z axis in object body frame
    :param float max_norm_Tx, max_norm_Ty, max_norm_Tz: maximum magnitude of torque about each of x, y, z axis in object body frame
    :param float n: no. of contacts
    :param list of np.array(3, 1) pos_b: position of contacts in body frame 
    :param list of np.array(3, 3) R_bc: contact frame (x: normal, y: tangential) in terms of body frame 
                                (rotates contact frame to body frame)
    :param list of float ncf: zero wrench normal contact force magnitude
    :param list of float tan: zero wrench tangential contact force magnitude and direction (+ve along dir defined by R_bc)
    :param list of float mu: tangential friction coefficient

    :return float min_gamma: where minimum normal contact force = normal component of (min_gamma * f_internal)
    '''

    wrench_checker = WrenchCheck(n, pos, R, ncf, tan_y, tan_z, mu)

    # collect unique nonzero wrenches
    possible_wrenches = []
    seen = set()
    for tx in [-max_norm_Tx, max_norm_Tx]:
        for ty in [-max_norm_Ty, max_norm_Ty]:
            for tz in [-max_norm_Tz, max_norm_Tz]:
                for ax in [-max_norm_accelx, max_norm_accelx]:
                    for ay in [-max_norm_accely, max_norm_accely]:
                        for az in [-max_norm_accelz, max_norm_accelz]:
                            possible_wrench = np.array([[tx],[ty],[tz],[ax],[ay],[az]])

                            # skip if zero wrench (trivially feasible)
                            # (makes binary search way quicker)
                            if np.allclose(possible_wrench, 0):
                                continue

                            # skip if duplicate possible wrench
                            # (makes binary search way quicker)
                            possible_duplicate = tuple(possible_wrench.flatten())
                            if possible_duplicate in seen:
                                continue
                            seen.add(possible_duplicate)

                            possible_wrenches.append(possible_wrench)

    def all_feasible(gamma):
        return all(wrench_checker.wrench_feasibility(gamma, possible_wrench) < wrench_checker.num_tol
                   for possible_wrench in possible_wrenches)

    # check geometric feasibility at high gamma
    if not all_feasible(1000):
        return None

    # binary search for minimum gamma
    lo, hi = 0.0, 1000.0
    for _ in range(60):  # 60 iterations → precision ~1e-15
        mid = (lo + hi) / 2
        if all_feasible(mid):
            hi = mid
        else:
            lo = mid

    return hi

if __name__ ==  "__main__":

    print('sign convention: z↑ x-> y⊗')

    # ->▢ <- from spatial_grasp_map.py
    n_contacts = 2
    pos_list = [np.array([[-0.05], [0], [0]]), np.array([[0.05], [0], [0]])]
    R_list = [np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), np.array([[-1, 0, 0], [0, 1, 0], [0, 0, 1]])]
    ncf_list = [1, 1]
    tany_list = [0, 0]
    tanz_list = [0, 0]
    mu_list = [1, 1]
    
    # Test 1: ->▢ <- with wrench ->
    print('Test 1: ->▢ <- with wrench ->')
    print(f'When fx=1 wrench, gamma = {min_gamma_for_accel(1, 0, 0, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 2: ->▢ <- with wrench ⊗
    print('Test 2: ->▢ <- with wrench ⊗')
    print(f'When fy=1 wrench, gamma = {min_gamma_for_accel(0, 1, 0, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 3: ->▢ <- with wrench ↑
    print('Test 3: ->▢ <- with wrench  ↑')
    print(f'When Tx=1 wrench, gamma = {min_gamma_for_accel(0, 0, 1, 0, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 4: ->▢ <- with wrench torque about x-axis
    print('Test 4: ->▢ <- with wrench torque about x-axis')
    print(f'When Tx=1 wrench, gamma = {min_gamma_for_accel(0, 0, 0, 1, 0, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 5: ->▢ <- with wrench torque about x-axis
    print('Test 5: ->▢ <- with wrench torque about y-axis')
    print(f'When Tx=1 wrench, gamma = {min_gamma_for_accel(0, 0, 0, 0, 1, 0, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    # Test 6: ->▢ <- with wrench torque about x-axis
    print('Test 6: ->▢ <- with wrench torque about z-axis')
    print(f'When Tx=1 wrench, gamma = {min_gamma_for_accel(0, 0, 0, 0, 0, 1, n_contacts, pos_list, R_list, ncf_list, tany_list, tanz_list, mu_list)}')

    print()


                